# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  datingappapi:
    image: datingappapi
    build:
      context: .
      dockerfile: DatingApp.API/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
