# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

networks:
  dating-network:
    driver: bridge

services:
  datingappapi:
    image: datingappapi
    build:
      context: .
      dockerfile: DatingApp.API/Dockerfile
    ports:
      - "8000:80"
    environment:
      - "ConnectionStrings:PostgresConnection=User ID=postgres;Password=password;Server=postgres-image;Port=5432;Database=petdating;Integrated Security=true;Pooling=true;"
    depends_on:
      - postgres-image
    networks:
      - dating-network

  postgres-image:
    image: postgres
    container_name: datingapp_postgress-image_1
    ports:
      - "5432:5432"
    restart: always
    environment:
      # POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "petdating"
    networks:
      - dating-network
